# Use Node.js as base image
FROM node:16-alpine as builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the React app
RUN npm run build

# Stage 2: Production environment
FROM nginx:alpine

# Copy build files from the previous stage
COPY --from=builder /app/build /usr/share/nginx/html

# Expose port 80
# EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]