# Use Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN pip3 install httpx==0.26.0 h11==0.14.0 httpcore==1.0.5

# Copy the rest of the application
COPY . .

# Set environment variables
ENV CACHE_SAVE_DIR="/home/nils/programming/story-translator/cache"
ENV PYTHONWARNINGS="ignore"

# Expose port if needed
# EXPOSE 5000

# Command to run the application
CMD ["flask", "--app", "main.py", "run", "--host", "0.0.0.0"]
