name: Create docker images

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      with:
        registry: harbor.u1.se
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    
    - name: Build and Push Backend Image
      working-directory: '/home/runner/work/story-translator/backend' 
      run: |
        docker build -t harbor.u1.se/story-translator/backend:latest -f Dockerfile .
        docker push harbor.u1.se/story-translator/backend:latest

    - name: Build and Push Frontend Image
      working-directory: './frontend'
      run: |
        docker build -t harbor.u1.se/story-translator/frontend:latest -f Dockerfile .
        docker push harbor.u1.se/story-translator/frontend:latest

