name: Create docker images

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      with:
        registry: harbor.u1.se
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Backend Image
      working-directory: './backend' 
      run: |
        docker build --no-cache -t harbor.u1.se/story-translator/backend:latest .
        docker push harbor.u1.se/story-translator/backend:latest

    - name: Build and Push Frontend Image
      working-directory: './frontend'
      run: |
        docker build --no-cache -t harbor.u1.se/story-translator/frontend:latest .
        docker push harbor.u1.se/story-translator/frontend:latest

